<?php

namespace JeuEchec\EchiquierBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PiecesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiecesRepository extends EntityRepository
{
}
