jeu_echec_echiquier_homepage:
    path:     /
    defaults: { _controller: "JeuEchecEchiquierBundle:Default:index" }
    
jeu_echec_echiquier_plateau:
    path:     /plateau
    defaults: { _controller: "JeuEchecEchiquierBundle:Echiquier:plateau" }
    
jeu_echec_echiquier_cases:
    path:     /voir{x}{y}
    defaults: { _controller: "JeuEchecEchiquierBundle:Echiquier:voir" }

jeu_echec_echiquier_deplacer:
    path:     /deplacer{x}{y}
    defaults: { _controller: "JeuEchecEchiquierBundle:Echiquier:deplacer" }
